openapi: 3.0.0
info:
  title: Your API Title
  description: Description of your API
  version: 1.0.0
paths:
  /product:
    get:
      summary: Get a list of product
      responses:
        '200':
          description: Successful response
  /user:
    get:
      summary: Get a list of user
      responses:
        '200':
          description: Successful response
